language: java

jdk:
  - oraclejdk8

env:
  global:
#    # BINTRAY_USER
#    - secure: "Yq+1rj9WV5DYzwhoM4dbNvoo7LgNfqfRjq3Z2E4YXzd7fd17y7NSlzIW1MzEU1Egi4rhmmu2qa/N8/0I4g3efwHHCZPgmqJzAkOuJK81y6QvnoXh2Q2WV5R7wvGzZ3W3M4AoYhrKpBCdTP2c94dfGb90TtjRo16KfqFCZPLawYsxjhknkhVFJm+z1B04VhgX5ePEQNgF23Tlg02tGuffKOGQjM2fwiK0wub5QGSlg8htmLtJ5QAW17LnOgyiSws8aiSg6lyB173i5SsjMoO9qCO48JTkh5y58JFSR2gYB9PNBY5xwISkfkFOoz7+UmeRczZxf5kNec39BTkhBfivS/co7rDMWFlm68YlNUJFFQZK8neq9mUDL5iLe7kod5MWp7+gwckdkw4Nkdadr8UGjHXY9tNxBLur/Xa9z3mGESlNFfd3TvHGFYWfCvYWs4bBd06XwldubyjPEwtHIb5u8zV7CdDHokKj4VZrrCB7UavC2+yH4/mSp9dzTbFjBK6JMkAU9GsJQS4HbvvR86SFooNKp0cmSVft63PVEnhJKyKcIh2mnJ8nVa5QzSBsZogPKNlqf094/XsDHdAjoyQYUvMgi9sAYtkrDdPTq78nY2lDNfJyFy4w40/I38z7lt6QkNkKpBiVnJqm2vvH9CyTJv27K779mV14gQTJegJMl4g="
#    # BINTRAY_KEY
#    - secure: "EGpqzC3hnOWxpvX72x1AK0DWoVd+Xv1Z9jJnJpJ9Y7zLWlfR8x5FgEj0cnpagORtVdBrS7f8TYWdIF5PD96cB5BAerFNiyi4+xrJ7DfvkFYmAs700TvP1hlwxLDLyZnkMoNTQ5ZDdpxFVslmlbF+eEgg9pZd4ZWfV4ejUEw44YLfFmWfh4FrLej9h/njJoQOtbGLUv9EsuMsiJ9N8F99LwUnJypwfBgvNg7GJEEcQ2kSPhM30gGit1z49lQWGeDmMj8GnsvgPKxr1q7B8anWnIrLyAZ7HnC16elEoBmCNCU7s+igYstRmVE8Ifq8ri3SWBVhsnDmNT8OEns8X/Whr93rRirNaDcugbltHl+9ricth86SPrWp+LORck59BxzI0KXOjeXTnzvFxGoOredrWa6CgjMaEbpum2hiWldO/YF2MK2o93fL1cKcmjg0dsPM/SPAGoeT2mNEvQmphiUQnMt17YOJIskcPhoeV48QHvz71brTqI70o6V3QuSAPbLB5/AoRkqXFhnQgC8Tu8fm7AxlWurRwWh4UyQ4Tf8wOHscKgAWSrKTpetOBHlISvP6U0ODka+lsqlDXEDklKMLuFhdflY0IRsryVO3k/UOGFywxP4ybJazsrZmcY9Jje2jWATznuFSiK1n2hhjX1EMhrqmpT9aF9YMxIM6axY/GH8="
#    # GPG_PASSPHRASE
#    - secure: "qhNYDRJJadLCIIFdGWTQzFtACoIr2On8eYLIjK8tD9X2AcEAaLtzA5vD7r5hZSet0+NUsG5gautXaFZoR9pqJVeFvdPdXjiHFiCNDK2aC4z1RTGyogzOwFmwdmamgcVB02mS/NUGIkjFng9Qj6m6NzPLTv/mrohVZL31TaYNbLnag73cPNyVfu9dc7/hTVJvvYNMWwXiCP8RnomL3lnrwEDdpVLJPuizG+mcJLwsJ0X7h2N16w16rhUETI2JuCjgaFhRqDlcFlEK7KYbq/QlyvyT6YA7gJTLsoE4+gaWuf2KxyupMoRD+0op9wWBy+/dJMCnZqUGRhPg9WDbQHlzdsKMSb4p2hahZnG4t3jtpLt8S2uDzpAAl9IoyzIP4eP3TWDMZZ7dwUP5iOblUZcJEk9qOuyM9OMZLTK9YYwtzny32QrFVc2PSeCJLc34NwZuMl+ER98hlVYUToj0vvn2QCwmBbDLpPJa7kw71rJErLaGo44dybozSKcAV1NrwjR3kUcVxMM0E/S0kvUNYRfDFbdHTY1tkbza0X5ujuR9B+vQ47kTCmgSgHQhnmcRjAY/SE/hfxjELZ179a8+gIgs8oArBEBMu0XOHB1MQWU4h7hkpNrc2inLb1lyW2iiDSE6yPyACwwZd+2t/yU13b1kHNDhhZReIVjK0yJKmXTH9Lc="

install: ./gradlew clean
script: ./gradlew test

#deploy:
#  - provider: script
#    script: ./gradlew bintrayUpload -p core
#    on:
#      tags: true

cache:
  directories:
    - ~/.gradle/
